apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: bitcoin-mainnet-bitcoind
spec:
  storageClassName: slow
  capacity:
    storage: "1000Gi"
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "bitcoind-mainnet-segwit-1"
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: bitcoin-mainnet-electrumx
spec:
  storageClassName: fast
  capacity:
    storage: "100Gi"
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "electrumx-bitcoin1"