kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mainnet-electrumx
  namespace: bitcoin
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Gi"
  volumeName: bitcoin-mainnet-electrumx