apiVersion: v1
kind: Service
metadata:
  name: mainnet-electrumx
  namespace: bitcoin
spec:
  ports:
    - name: electrum
      port: 50001
      protocol: TCP
      targetPort: 50001
    - name: electrum-ssl
      port: 50002
      protocol: TCP
      targetPort: 50002
  type: LoadBalancer
  selector:
    app: mainnet-electrumx